Repository dsc-sookmyung/2024-02-Android-Study, pull requests merged in 2024-11, with the labels that each got.

#44 [WEEK05 김나현] Preferences Datastore, Room을 활용한 로컬 데이터 저장
  README.md
  app/build.gradle.kts
  app/src/main/java/com/gdg/android/MainActivity.kt
  app/src/main/java/com/gdg/android/UserCreateScreen.kt
  app/src/main/java/com/gdg/android/UserDao.kt
  app/src/main/java/com/gdg/android/UserDatabase.kt
  app/src/main/java/com/gdg/android/UserEntity.kt
  app/src/main/java/com/gdg/android/UserScreen.kt
Labels: 💚WEEK05, 🍀나현

#46 [WEEK05 백서연] 직접 유저 추가/삭제 기능 구현
  .gitignore
  .idea/deploymentTargetSelector.xml
  .idea/inspectionProfiles/Project_Default.xml
  README.md
  app/build.gradle.kts
  app/src/main/java/com/gdg/android/MainActivity.kt
  app/src/main/java/com/gdg/android/UserCreateScreen.kt
  app/src/main/java/com/gdg/android/UserDao.kt
  app/src/main/java/com/gdg/android/UserDatabase.kt
  app/src/main/java/com/gdg/android/UserEntity.kt
  app/src/main/java/com/gdg/android/UserScreen.kt
Labels: 💚WEEK05, 🐱 서연

#50 [WEEK05 조영서] Preferences Datastore, Room을 활용한 로컬 데이터 저장
  app/build.gradle.kts
  app/src/main/java/com/gdg/android/presentation/LoginPage.kt
  app/src/main/java/com/gdg/android/presentation/MainActivity.kt
  app/src/main/java/com/gdg/android/presentation/ProfileScreen.kt
  app/src/main/java/com/gdg/android/presentation/UserCreateScreen.kt
  app/src/main/java/com/gdg/android/presentation/UserScreen.kt
  app/src/main/java/com/gdg/android/room/UserDao.kt
  app/src/main/java/com/gdg/android/room/UserDatabase.kt
  app/src/main/java/com/gdg/android/room/UserEntity.kt
  gradle/libs.versions.toml
Labels: 💚WEEK05, 🦊 영서

#49 [WEEK05 이현진] Preferences Datastore, Room을 활용한 로컬 데이터 저장
  .idea/deploymentTargetSelector.xml
  README.md
  app/build.gradle.kts
  app/src/main/java/com/gdg/android/login/LoginScreen.kt
  app/src/main/java/com/gdg/android/main/MainActivity.kt
  app/src/main/java/com/gdg/android/main/MainViewModel.kt
  app/src/main/java/com/gdg/android/user/UserCreateScreen.kt
  app/src/main/java/com/gdg/android/user/UserDao.kt
  app/src/main/java/com/gdg/android/user/UserDatabase.kt
  app/src/main/java/com/gdg/android/user/UserEntity.kt
  app/src/main/java/com/gdg/android/user/UserScreen.kt
Labels: 💚WEEK05, 🐤 현진

#58 [WEEK06] 스타일 가이드와 디자인 패턴
  .idea/deploymentTargetSelector.xml
  app/build.gradle.kts
  app/src/main/java/com/gdg/android/MainActivity.kt
  app/src/main/java/com/gdg/android/MainViewModel.kt
  app/src/main/java/com/gdg/android/UserScreen.kt
  app/src/main/java/com/gdg/android/UserViewModel.kt
  app/src/main/java/com/gdg/android/ui/theme/Color.kt
  app/src/main/java/com/gdg/android/ui/theme/Type.kt
  app/src/main/res/font/pretendard_black.otf
  app/src/main/res/font/pretendard_bold.otf
  app/src/main/res/font/pretendard_extrabold.otf
  app/src/main/res/font/pretendard_extralight.otf
  app/src/main/res/font/pretendard_light.otf
  app/src/main/res/font/pretendard_medium.otf
  app/src/main/res/font/pretendard_regular.otf
  app/src/main/res/font/pretendard_semibold.otf
  app/src/main/res/font/pretendard_thin.otf
Labels: 💚WEEK06, 🐱 서연

#53 [WEEK06 김나현] 스타일 가이드와 디자인 패턴
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/gdg/android/GDGApp.kt
  app/src/main/java/com/gdg/android/MainActivity.kt
  app/src/main/java/com/gdg/android/MainViewModel.kt
  app/src/main/java/com/gdg/android/UserScreen.kt
  app/src/main/java/com/gdg/android/UserViewModel.kt
  app/src/main/java/com/gdg/android/ui/theme/Color.kt
  app/src/main/java/com/gdg/android/ui/theme/Type.kt
  app/src/main/res/font/kimjungchulmyungjo_bold.otf
  app/src/main/res/font/kimjungchulmyungjo_light.otf
  app/src/main/res/font/kimjungchulmyungjo_regular.otf
  app/src/main/res/font/pretendard_bold.otf
  app/src/main/res/font/pretendard_medium.otf
  app/src/main/res/font/pretendard_regular.otf
  app/src/main/res/font/pretendard_semibold.otf
  build.gradle.kts
Labels: 💚WEEK06, 🍀나현

#59 [WEEK06 이현진] 스타일 가이드와 디자인 패턴
  app/build.gradle.kts
  app/src/main/java/com/gdg/android/login/LoginScreen.kt
  app/src/main/java/com/gdg/android/main/MainActivity.kt
  app/src/main/java/com/gdg/android/main/MainViewModel.kt
  app/src/main/java/com/gdg/android/ui/theme/Color.kt
  app/src/main/java/com/gdg/android/ui/theme/Type.kt
  app/src/main/java/com/gdg/android/user/UserScreen.kt
  app/src/main/java/com/gdg/android/user/UserViewModel.kt
  app/src/main/res/font/pretendard_bold.otf
  app/src/main/res/font/pretendard_medium.otf
  app/src/main/res/font/pretendard_regular.otf
  app/src/main/res/font/pretendard_semibold.otf
  app/src/main/res/font/pretendard_thin.otf
Labels: 💚WEEK06, 🐤 현진
