Repository dsc-sookmyung/2024-02-Android-Study, pull requests merged in 2024-10, with the labels that each got.

#12 [WEEK01 이가을] 리드미 작성
  README.md
Labels: 💚 WEEK01, 🐰 가을

#15 #14 [WEEK02] 프로필과 수강 과목들을 볼 수 있는 메인페이지 작성
  .idea/deploymentTargetSelector.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/gdg/android/MainActivity.kt
Labels: 💚WEEK02, 🐱 서연

#22 [WEEK02 조영서] Android UI 구현 기초
  .idea/deploymentTargetSelector.xml
  .idea/gradle.xml
  .idea/kotlinc.xml
  .idea/misc.xml
  .idea/vcs.xml
  README.md
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/gdg/android/MainActivity.kt
  gradle/libs.versions.toml
Labels: 💚WEEK02, 🦊 영서

#21 [WEEK02 이현진] Android UI 구현 기초
  .gitignore
  .idea/.gitignore
  .idea/.name
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/compiler.xml
  .idea/deploymentTargetSelector.xml
  .idea/gradle.xml
  .idea/kotlinc.xml
  .idea/migrations.xml
  .idea/misc.xml
  .idea/other.xml
  .idea/vcs.xml
  README.md
  app/.gitignore
  app/build.gradle.kts
  app/proguard-rules.pro
  app/src/androidTest/java/com/gdg/android/ExampleInstrumentedTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/gdg/android/MainActivity.kt
  app/src/main/java/com/gdg/android/ui/theme/Color.kt
  app/src/main/java/com/gdg/android/ui/theme/Theme.kt
  app/src/main/java/com/gdg/android/ui/theme/Type.kt
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  app/src/main/res/xml/backup_rules.xml
  app/src/main/res/xml/data_extraction_rules.xml
  app/src/test/java/com/gdg/android/ExampleUnitTest.kt
  build.gradle.kts
  gradle.properties
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle.kts
Labels: 💚WEEK02, 🐤 현진

#27 #26 [WEEK03] 로그인 페이지 작성 및 메인 페이지와 연결
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/deploymentTargetSelector.xml
  .idea/vcs.xml
  app/build.gradle.kts
  app/src/main/java/com/gdg/android/MainActivity.kt
  app/src/main/res/values/strings.xml
Labels: 💚WEEK03, 🐱 서연

#29 [WEEK03 김나현] Android UI 구현 심화
  .idea/deploymentTargetSelector.xml
  app/build.gradle.kts
  app/src/main/java/com/gdg/android/MainActivity.kt
  gradle/libs.versions.toml
Labels: 💚WEEK03, 🍀나현

#33 [WEEK03 조영서] Android UI 구현 심화
  .idea/deploymentTargetSelector.xml
  .idea/misc.xml
  .idea/other.xml
  app/build.gradle.kts
  app/src/main/java/com/gdg/android/MainActivity.kt
Labels: 💚WEEK03, 🦊 영서

#32 [WEEK03 이현진] Android UI 구현 심화
  .idea/deploymentTargetSelector.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/misc.xml
  app/build.gradle.kts
  app/src/main/java/com/gdg/android/MainActivity.kt
Labels: 💚WEEK03, 🐤 현진

#37 [WEEK04] 유저 목록 버튼 추가 및 유저 목록 페이지 만들기
  .idea/deploymentTargetSelector.xml
  app/build.gradle.kts
  app/src/main/java/com/gdg/android/ApiFactory.kt
  app/src/main/java/com/gdg/android/MainActivity.kt
  app/src/main/java/com/gdg/android/MainViewModel.kt
  app/src/main/java/com/gdg/android/ResponseUserDto.kt
  app/src/main/java/com/gdg/android/UserScreen.kt
  app/src/main/java/com/gdg/android/UserService.kt
  gradle/libs.versions.toml
Labels: 💚WEEK04, 🐱 서연

#41 [WEEK04 이현진] Retrofit2를 활용한 서버통신
  .idea/deploymentTargetSelector.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/gdg/android/api/ApiFactory.kt
  app/src/main/java/com/gdg/android/api/ResponseUserDto.kt
  app/src/main/java/com/gdg/android/api/UserService.kt
  app/src/main/java/com/gdg/android/main/MainActivity.kt
  app/src/main/java/com/gdg/android/main/MainViewModel.kt
  app/src/main/java/com/gdg/android/user/UserScreen.kt
  gradle/libs.versions.toml
Labels: 💚WEEK04, 🐤 현진

#39 [WEEK04 김나현] Retrofit2를 활용한 서버통신
  .gitignore
  app/build.gradle.kts
  app/src/main/java/com/gdg/android/ApiFactory.kt
  app/src/main/java/com/gdg/android/MainActivity.kt
  app/src/main/java/com/gdg/android/MainViewModel.kt
  app/src/main/java/com/gdg/android/ResponseUserDto.kt
  app/src/main/java/com/gdg/android/UserScreen.kt
  app/src/main/java/com/gdg/android/UserService.kt
  gradle/libs.versions.toml
Labels: 💚WEEK04, 🍀나현

#42 [WEEK04 조영서] Retrofit2를 활용한 서버통신
  .gitignore
  .idea/deploymentTargetSelector.xml
  .idea/kotlinc.xml
  .idea/vcs.xml
  README.md
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/gdg/android/MainActivity.kt
  app/src/main/java/com/gdg/android/api/ApiFactory.kt
  app/src/main/java/com/gdg/android/api/ResponseUserDto.kt
  app/src/main/java/com/gdg/android/api/UserService.kt
  app/src/main/java/com/gdg/android/presentation/LoginPage.kt
  app/src/main/java/com/gdg/android/presentation/MainActivity.kt
  app/src/main/java/com/gdg/android/presentation/MainViewModel.kt
  app/src/main/java/com/gdg/android/presentation/ProfileScreen.kt
  app/src/main/java/com/gdg/android/presentation/UserScreen.kt
  gradle/libs.versions.toml
Labels: 💚WEEK04, 🦊 영서
